CREATE TABLE tblCronQueue ( fldCronQueueID varchar(11) NOT NULL DEFAULT '', fldRef varchar(11) NOT NULL DEFAULT '0', fldCommand varchar(255) NOT NULL DEFAULT '', fldPriority char(3) NOT NULL DEFAULT '0', fldStatus char(10) NOT NULL DEFAULT 'NEW', fldRunTime varchar(30) DEFAULT NULL, fldReturnValue char(3) DEFAULT NULL, fldReturnOutput varchar(255) DEFAULT NULL, PRIMARY KEY (fldCronQueueID) );
CREATE TABLE tblGroup ( fldGroupID varchar(10) NOT NULL DEFAULT '', fldName varchar(50) NOT NULL DEFAULT '', fldLongName varchar(240) NOT NULL DEFAULT '', PRIMARY KEY (fldGroupID));
CREATE TABLE tblUser ( fldUserID varchar(10) NOT NULL DEFAULT '', fldDomain varchar(50) NOT NULL DEFAULT '', fldUser varchar(100) NOT NULL DEFAULT '', fldSalutation varchar(10) DEFAULT NULL, fldFirstName varchar(50) DEFAULT NULL, fldLastName varchar(50) DEFAULT NULL, fldPreferedName varchar(50) DEFAULT NULL, fldPassword varchar(100) NOT NULL DEFAULT '', fldAltDomain varchar(100) DEFAULT NULL, fldLevel char(3) NOT NULL DEFAULT '7', fldCreated varchar(25) NOT NULL DEFAULT '', fldModified varchar(25) NOT NULL DEFAULT '', fldLastLogin varchar(25) NOT NULL DEFAULT '', fldTimeZone varchar(10) NOT NULL DEFAULT '', fldFails char(3) NOT NULL DEFAULT '0', PRIMARY KEY (fldUserID));
CREATE TABLE tblNextNumber ( fldNextNumberID char(10) NOT NULL DEFAULT '', fldTable char(50) NOT NULL DEFAULT '', fldNext int(6) NOT NULL DEFAULT '0', fldFormat char(10) NOT NULL DEFAULT '', fldComment char(100) NOT NULL DEFAULT '', fldTableChecksum char(50) DEFAULT NULL, PRIMARY KEY (fldNextNumberID));
CREATE TABLE tblFileCheck ( fldFileCheckID char(10) NOT NULL DEFAULT '', fldFileName char(255) NOT NULL DEFAULT '', fldSize char(20) NOT NULL DEFAULT '', fldCRC char(50) NOT NULL DEFAULT 'DATA', PRIMARY KEY (fldFileCheckID));
CREATE TABLE tblSecPrivileges ( fldSecPrivilegesID varchar(10) NOT NULL DEFAULT '0', fldName varchar(50) DEFAULT NULL, fldAction varchar(50) DEFAULT NULL, PRIMARY KEY (fldSecPrivilegesID));
CREATE TABLE tblCrossSiteProtection ( fldCrossSiteProtectionID varchar(12) NOT NULL DEFAULT '', fldUniqueID varchar(50) DEFAULT NULL, fldExpiryDate int(10) DEFAULT NULL, PRIMARY KEY (fldCrossSiteProtectionID));
CREATE TABLE tblScheduler ( fldSchedulerID varchar(11) NOT NULL DEFAULT '', fldCommand varchar(255) NOT NULL DEFAULT '', fldActive char(3) NOT NULL DEFAULT 'Yes', fldStartTime varchar(40) NOT NULL DEFAULT '', fldCron varchar(100) NOT NULL DEFAULT '', fldLastRun varchar(40) NOT NULL DEFAULT '', PRIMARY KEY (fldSchedulerID));
CREATE TABLE tblUserType ( fldUserTypeID varchar(20) NOT NULL DEFAULT '', fldUserTypeValue char(3) NOT NULL DEFAULT '', fldUserTypeName varchar(20) NOT NULL DEFAULT '');
CREATE TABLE tblLoginAttempt ( fldLoginAttemptID varchar(12) NOT NULL DEFAULT '', fldUsername varchar(100) DEFAULT NULL, fldPassword varchar(100) DEFAULT NULL, fldAgent varchar(200) DEFAULT NULL, fldRemoteAddress varchar(100) DEFAULT NULL, PRIMARY KEY (fldLoginAttemptID));
CREATE TABLE tblTimeZone ( fldTimeZoneID char(4) NOT NULL, fldDescription char(50) NOT NULL DEFAULT '', fldTime char(20) NOT NULL DEFAULT '', fldCode char(10) NOT NULL DEFAULT '', PRIMARY KEY (fldTimeZoneID));
CREATE TABLE tblUserGroupMap ( fldUserGroupMapID char(10) NOT NULL DEFAULT '', fldUserID char(10) NOT NULL DEFAULT '', fldGroupID char(10) NOT NULL DEFAULT '', PRIMARY KEY (fldUserGroupMapID));
CREATE TABLE tblSecPrivUserMap ( fldSecPrivUserMapID char(10) NOT NULL DEFAULT '', fldUserID char(10) NOT NULL DEFAULT '', fldGroupID char(10) NOT NULL DEFAULT '', fldLevelID char(10) NOT NULL DEFAULT '', fldPrivilegeID char(10) NOT NULL DEFAULT '', fldStartDate int(25) DEFAULT '0', fldEndDate int(25) DEFAULT '0', fldLoginAction varchar(100) NOT NULL DEFAULT '', PRIMARY KEY (fldSecPrivUserMapID));
CREATE TABLE tblConfig (fldUserID varchar (11) NOT NULL, fldKey varchar (100) NOT NULL, fldValue varchar (1000) DEFAULT NULL, PRIMARY KEY (fldUserID, fldKey));
CREATE TABLE tblMigration (fldMigrationID varchar (11) NOT NULL, fldRun char (5) NOT NULL, fldClass varchar (200) NOT NULL, fldMethod varchar (50) NOT NULL, fldReadTime datetime NOT NULL DEFAULT current_timestamp, PRIMARY KEY (fldMigrationID));


INSERT INTO tblGroup (fldGroupID, fldName, fldLongName) VALUES ('GR001', 'Everyone', 'Group of all people');
INSERT INTO tblUser (fldUserID, fldDomain, fldUser, fldSalutation, fldFirstName, fldLastName, fldPreferedName, fldPassword, fldAltDomain, fldLevel, fldCreated, fldModified, fldLastLogin, fldTimeZone, fldFails) VALUES ('UI0016', 'nextdc.com', 'brett@brettdutton.com', 'Mr', 'Brett', 'Dutton', 'Brett', 'cc9755e8674f5866a09415735db60028', NULL, '0', '1290121086', '', '1445918013', '10', '0');
INSERT INTO tblUser (fldUserID, fldDomain, fldUser, fldSalutation, fldFirstName, fldLastName, fldPreferedName, fldPassword, fldAltDomain, fldLevel, fldCreated, fldModified, fldLastLogin, fldTimeZone, fldFails) VALUES ('UI0015', 'onedc.com',  'dev.ops@nextdc.com', 'Mr', 'Dev', 'Ops', 'Dev', '5f4dcc3b5aa765d61d8327deb882cf99', NULL, '0', '1290121086', '', '1445918013', '10', '0');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN01', 'tblNextNumber', 20, 'NN00', 'Special table that is used to generate unique ID', 'ac15bc45e964c78aaadd379cdbe36b02');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN02', 'tblUser', 23, 'UI0000', 'Users that are in the system', '8227776474896ee509daa2161a0de041');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN03', 'tblUserType', 10, 'UT00', 'Types of Users', '72a866106f67db2384c4819025a60a19');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN04', 'tblGroup', 5, 'GR000', '', '3c77f3a99574e515a0fc9ba914b123ad');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN05', 'tblTimeZone', 53, 'TZ00', '', '456583b63a30a007d3d1a1addaac79a8');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN06', 'tblUserGroupMap', 1, 'GRM000', '', '475094cd5745fef99187360ab79b5fec');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN07', 'tblSecPrivileges', 33, 'PR000', 'Description of the priviliages in the system', '404be3de8368d686e67301e8b5eea90c');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN08', 'tblSecPrivUserMap', 33, 'PM0000', 'Maps the priviliages to user, group or level', 'eff4d9862510f8a3a20f7ba2f07e874e');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN09', 'tblCrossSiteProtection', 119, 'CS00000000', 'Auto Inserted by dbNextNumber', 'd41d8cd98f00b204e9800998ecf8427e');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN10', 'tblFileCheck', 1, 'FC0000000', 'File Check Table', '7db809227d6d4a5af21963e00ade7963');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN11', 'tblLoginAttempt', 74, 'LA0000', 'List of the login attempts', '17bee6cd741eddb4366a34fbda7682aa');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN12', 'tblCronQueue', 9, 'CQ000000', 'Table of all the Cron Jobs', '74f6553a7935e564102ac6370b41cf1d');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN13', 'tblScheduler', 4, 'SH00000', 'Scheduler Jobs', '43a5940f2e7c761932d9d1312b762a08');
INSERT INTO tblNextNumber (fldNextNumberID, fldTable, fldNext, fldFormat, fldComment, fldTableChecksum) VALUES ('NN14', 'tblMigration', 1, 'M000', 'Table of all the Migrations', '74f6553a7935e564102ac6370b41cf1d');
INSERT INTO tblUserType (fldUserTypeID, fldUserTypeValue, fldUserTypeName) VALUES ('UT01', '0', 'God');
INSERT INTO tblUserType (fldUserTypeID, fldUserTypeValue, fldUserTypeName) VALUES ('UT03', '1', 'Super Admin');
INSERT INTO tblUserType (fldUserTypeID, fldUserTypeValue, fldUserTypeName) VALUES ('UT04', '2', 'Site Admin');
INSERT INTO tblUserType (fldUserTypeID, fldUserTypeValue, fldUserTypeName) VALUES ('UT05', '3', 'Manager');
INSERT INTO tblUserType (fldUserTypeID, fldUserTypeValue, fldUserTypeName) VALUES ('UT06', '4', 'Assist Manager');
INSERT INTO tblUserType (fldUserTypeID, fldUserTypeValue, fldUserTypeName) VALUES ('UT07', '5', 'Staff');
INSERT INTO tblUserType (fldUserTypeID, fldUserTypeValue, fldUserTypeName) VALUES ('UT08', '6', 'User');
INSERT INTO tblUserType (fldUserTypeID, fldUserTypeValue, fldUserTypeName) VALUES ('UT09', '7', 'Guest');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ01', 'Hawaii-Aleutian Standard Time', 'GMT - 10 hours', '-10');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ02', 'Alaska Standard Time', 'GMT - 09 hours', '-9');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ03', 'Hawaii-Aleutian Daylight Time', 'GMT - 09 hours', '-9');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ04', 'Heure Normale du Yukon', 'GMT - 09 hours', '-9');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ05', 'Alaska Daylight Time', 'GMT - 08 hours', '-8');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ06', 'Heure Avanc�e du Yukon', 'GMT - 08 hours', '-8');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ07', 'Heure Normale du Pacifique', 'GMT - 08 hours', '-8');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ08', 'Pacific Standard Time', 'GMT - 08 hours', '-8');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ09', 'Heure Avanc�e du Pacifique', 'GMT - 07 hours', '-7');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ10', 'Heure Normale des Rocheuses', 'GMT - 07 hours', '-7');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ11', 'Mountain Standard Time', 'GMT - 07 hours', '-7');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ12', 'Pacific Daylight Time', 'GMT - 07 hours', '-7');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ13', 'Central Standard Time', 'GMT - 06 hours', '-6');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ14', 'Heure Avanc�e des Rocheuses', 'GMT - 06 hours', '-6');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ15', 'Heure Normale du Centre', 'GMT - 06 hours', '-6');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ16', 'Mountain Daylight Time', 'GMT - 06 hours', '-6');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ17', 'Central Daylight Time', 'GMT - 05 hours', '-5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ18', 'Eastern Standard Time', 'GMT - 05 hours', '-5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ19', 'Heure Avanc�e du Centre', 'GMT - 05 hours', '-5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ20', 'Heure Normale de l''Est', 'GMT - 05 hours', '-5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ21', 'Atlantic Standard Time', 'GMT - 04 hours', '-4');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ22', 'Eastern Daylight Time', 'GMT - 04 hours', '-4');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ23', 'Heure Avanc�e de l''Est', 'GMT - 04 hours', '-4');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ24', 'Heure Normale de l''Atlantique', 'GMT - 04 hours', '-4');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ25', 'Heure Normale de Terre-Neuve', 'GMT - 03:30 hours', '-3.5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ26', 'Newfoundland Standard Time', 'GMT - 03:30 hours', '-3.5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ27', 'Atlantic Daylight Time', 'GMT - 03 hours', '-3');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ28', 'Heure Avanc�e de l''Atlantique', 'GMT - 03 hours', '-3');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ29', 'Heure Avanc�e de Terre-Neuve', 'GMT - 02:30 hours', '-2.5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ30', 'Newfoundland Daylight Time', 'GMT - 02:30 hours', '-2.5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ31', 'Greenwich Mean Time', 'GMT  00', '0');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ32', 'British Summer Time', 'GMT + 01 hour', '1');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ33', 'Central European Time', 'GMT + 01 hour', '1');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ34', 'Irish Summer Time', 'GMT + 01 hour', '1');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ35', 'Mitteleurop�ische Zeit', 'GMT + 01 hour', '1');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ36', 'Western European Summer Time', 'GMT + 01 hour', '1');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ37', 'Central European Summer Time', 'GMT + 02 hours', '2');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ38', 'Eastern European Time', 'GMT + 02 hours', '2');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ39', 'Mitteleurop�ische Sommerzeit', 'GMT + 02 hours', '2');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ40', 'Eastern European Summer Time', 'GMT + 03 hours', '3');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ41', 'Christmas Island Time', 'GMT + 07 hours', '7');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ42', 'Australian Western Standard Time', 'GMT + 08 hours', '8');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ43', 'Western Standard Time', 'GMT + 08 hours', '8');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ44', 'Australian Central Standard Time', 'GMT + 09:30 hours', '9.5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ45', 'Central Standard Time', 'GMT + 09:30 hours', '9.5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ46', 'Australian Eastern Standard Time', 'GMT + 10 hours', '10');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ47', 'Eastern Standard Time', 'GMT + 10 hours', '10');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ48', 'Australian Central Daylight Time', 'GMT + 10:30 hours', '10.5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ49', 'Central Daylight Time', 'GMT + 10:30 hours', '10.5');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ50', 'Australian Eastern Daylight Time', 'GMT + 11 hours', '11');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ51', 'Eastern Daylight Time', 'GMT + 11 hours', '11');
INSERT INTO tblTimeZone (fldTimeZoneID, fldDescription, fldTime, fldCode) VALUES ('TZ52', 'Norfolk (Island) Time', 'GMT + 11:30 hours', '11.5');

INSERT INTO tblSecPrivileges (fldSecPrivilegesID, fldName, fldAction) VALUES ('PR001', 'Full Access to Everything', '%');
INSERT INTO tblSecPrivileges (fldSecPrivilegesID, fldName, fldAction) VALUES ('PR002', 'Login', '%Login%');
INSERT INTO tblSecPrivileges (fldSecPrivilegesID, fldName, fldAction) VALUES ('PR003', 'CLI', '%CLI%');
INSERT INTO tblSecPrivileges (fldSecPrivilegesID, fldName, fldAction) VALUES ('PR008', 'General Administration', '%Admin%');
INSERT INTO tblSecPrivileges (fldSecPrivilegesID, fldName, fldAction) VALUES ('PR009', 'User Configuration Management', '%UserConfigManager%');
INSERT INTO tblSecPrivileges (fldSecPrivilegesID, fldName, fldAction) VALUES ('PR010', 'Database Management', '%DBManager%');
INSERT INTO tblSecPrivileges (fldSecPrivilegesID, fldName, fldAction) VALUES ('PR013', 'Location on the Images', '%ImagePositionLocator%');
INSERT INTO tblSecPrivileges (fldSecPrivilegesID, fldName, fldAction) VALUES ('PR014', 'System Administration', '%SuperAdmin%');
INSERT INTO tblSecPrivileges (fldSecPrivilegesID, fldName, fldAction) VALUES ('PR021', 'Captcha', '%Captcha%');
INSERT INTO tblSecPrivileges (fldSecPrivilegesID, fldName, fldAction) VALUES ('PR022', 'Edit My Account', '%Admin__editAccount%');
INSERT INTO tblSecPrivileges (fldSecPrivilegesID, fldName, fldAction) VALUES ('PR031', 'JackBooted Controllers', '%Jack%');

INSERT INTO tblSecPrivUserMap (fldSecPrivUserMapID, fldUserID, fldGroupID, fldLevelID, fldPrivilegeID, fldStartDate, fldEndDate, fldLoginAction) VALUES ('PM0010', '', '', '7', 'PR002', 0, 0, '');
INSERT INTO tblSecPrivUserMap (fldSecPrivUserMapID, fldUserID, fldGroupID, fldLevelID, fldPrivilegeID, fldStartDate, fldEndDate, fldLoginAction) VALUES ('PM0003', '', '', '7', 'PR003', 0, 0, '');
INSERT INTO tblSecPrivUserMap (fldSecPrivUserMapID, fldUserID, fldGroupID, fldLevelID, fldPrivilegeID, fldStartDate, fldEndDate, fldLoginAction) VALUES ('PM0011', '', '', '0', 'PR001', 0, 0, '');
INSERT INTO tblSecPrivUserMap (fldSecPrivUserMapID, fldUserID, fldGroupID, fldLevelID, fldPrivilegeID, fldStartDate, fldEndDate, fldLoginAction) VALUES ('PM0012', '', '', '3', 'PR008', 0, 0, '\Jackbooted\Admin\Login->index()');
INSERT INTO tblSecPrivUserMap (fldSecPrivUserMapID, fldUserID, fldGroupID, fldLevelID, fldPrivilegeID, fldStartDate, fldEndDate, fldLoginAction) VALUES ('PM0013', '', '', '0', 'PR010', 0, 0, '\Jackbooted\Admin\Login->index()');
INSERT INTO tblSecPrivUserMap (fldSecPrivUserMapID, fldUserID, fldGroupID, fldLevelID, fldPrivilegeID, fldStartDate, fldEndDate, fldLoginAction) VALUES ('PM0014', '', '', '3', 'PR009', 0, 0, '\Jackbooted\Admin\Login->index()');
INSERT INTO tblSecPrivUserMap (fldSecPrivUserMapID, fldUserID, fldGroupID, fldLevelID, fldPrivilegeID, fldStartDate, fldEndDate, fldLoginAction) VALUES ('PM0017', '', '', '0', 'PR014', 0, 0, '\Jackbooted\Admin\Login->index()');
INSERT INTO tblSecPrivUserMap (fldSecPrivUserMapID, fldUserID, fldGroupID, fldLevelID, fldPrivilegeID, fldStartDate, fldEndDate, fldLoginAction) VALUES ('PM0018', '', '', '3', 'PR013', 0, 0, '\Jackbooted\Admin\Login->index()');
INSERT INTO tblSecPrivUserMap (fldSecPrivUserMapID, fldUserID, fldGroupID, fldLevelID, fldPrivilegeID, fldStartDate, fldEndDate, fldLoginAction) VALUES ('PM0019', '', 'GR001', '', 'PR021', 0, 0, '');
INSERT INTO tblSecPrivUserMap (fldSecPrivUserMapID, fldUserID, fldGroupID, fldLevelID, fldPrivilegeID, fldStartDate, fldEndDate, fldLoginAction) VALUES ('PM0020', '', '', '6', 'PR022', 0, 0, '\Jackbooted\Admin\Login->index()');
INSERT INTO tblSecPrivUserMap (fldSecPrivUserMapID, fldUserID, fldGroupID, fldLevelID, fldPrivilegeID, fldStartDate, fldEndDate, fldLoginAction) VALUES ('PM0031', '', '', '6', 'PR031', 0, 0, '\Jackbooted\Admin\Login->index()');

CREATE INDEX tblNextNumber_fldTable ON tblNextNumber (fldTable);
CREATE INDEX tblFileCheck_fldFileName ON tblFileCheck (fldFileName);
CREATE INDEX tblCrossSiteProtection_fldUniqueID_idx ON tblCrossSiteProtection (fldUniqueID);
CREATE INDEX tblCrossSiteProtection_fldExpiryDate_idx ON tblCrossSiteProtection (fldExpiryDate);
CREATE INDEX tblUser_fldDomain ON tblUser (fldDomain);
